### ISSUE TITLE
Can't figure out how to add an NPC varient to the spawn table

### ISSUE THREAD

**Issue by FerriFinder** [supersonic1999/ZombieInvasion#18]
I know it's a tricky issue since say combine elites don't have a unique name, just a variant of npc_combine_s. Is there a work around?

**Comment by Zoidberg656** [comment]
You can go to the ragdolls, find the Combine Elite, right click and copy to clipboard, then paste the "models/Combine_Super_Soldier.mdl" where it says Model above NPC. 

You can also edit the health since Elite have more health if I recall correctly.

https://developer.valvesoftware.com/wiki/Npc_combine_s
